repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-json
      - id: check-xml
      - id: check-toml
      - id: check-yaml
        exclude: .gitlab-ci
      - id: check-added-large-files
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md,markdown"]
      - id: check-added-large-files
        args: [ '--maxkb=512' ]
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.277
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.9.0
    hooks:
      - id: pretty-format-toml
        exclude: poetry.lock
        args: [--autofix]
  - repo: https://github.com/python-poetry/poetry
    rev: '1.5.0'
    hooks:
      - id: poetry-check
      - id: poetry-export
